export const STATUS_MESSAGE = {
  userAlredyExists: "This user already exists",
  unauthorized: "Unauthorized",
  badRequest: "Bad request",
  ok: "Ok",
  signupTitle: "Create user",
  signUpCreate: "Account has been successfully created",
  signUpError: "Account already exists",
  loginTitle: "Login user",
  loginDescription: "User with token",
  loginError: "Wrong login or password",
  createPill: "Create new pill",
  creaatePillStatus: "Pill has been successfully created",
  createPillError: "Something wrong",
  getPillsTitle: "Get pills",
  getPillsStatus: "Pills has been successfully get",
  getPillError: "Something wrong",
  updatePillTitle: "Update pill",
  updatePillStatus: "Pill has been successfully update",
  updatePillError: "Something wrong"
};
